defaults:
  - hydra/sweeper: optuna
  - hydra/hydra_logging: none
  - hydra/job_logging: none

hydra:
    mode: MULTIRUN
    sweeper:
        sampler:
            _target_: optuna.samplers.TPESampler
            seed: 123
            consider_prior: true
            prior_weight: 1.0
            consider_magic_clip: true
            consider_endpoints: false
            n_startup_trials: 10
            n_ei_candidates: 24
            multivariate: false
            warn_independent_sampling: true


        n_trials: 100 
        direction: maximize
        params:
#          +n: 5,10,15
#          +AFLINK: True,False
#          +BoT: True,False
#          +EMA: True,False
#          +EMA_alpha: 0.1,0.9,1.0
#          +MC: True,False
#          +MC_lambda: 0.7,0.8,1
#          +NSA: True,False
#          +max_age: 100,1500,2000
          +max_iou_distance: 1, 100, 1000
          +min_confidence: 0.6, 0.9
 #         +woC: True, False
#          +nn_budget: 50, 70, 90
#          +n_init: 1, 10,20
          +min_detection_height: 0, 10, 20