COMMON_PREFIX: "/Users/aleksandrsimonyan/Desktop/deepmind_updated/"

arguments:
  logger_path: 
  AFLINK: false
  BoT: true
  ECC: false
  EMA: true
  EMA_alpha: 0.99
  GSI: false
  MC: false
  MC_lambda: 0.98
  NSA: true
  dir_save: null
  display: False
  max_age: 15
  max_cosine_distance: 0.4
  max_iou_distance: 0.9
  min_confidence: 1.0e-05
  min_detection_height: 0
  n_init: 3
  nms_max_overlap: 0.9
  nn_budget: 20
  path_AFLink: data/ext_models/AFLink_epoch20.pth
  root_dataset: data/preds
  video_directory: data/videos/train/
  woC: true
  device: 'cpu'

#main_dir_path: /Users/aleksandrsimonyan/Desktop/test/video_1_sequence_dir/
prepare_files:
  config_file: /Users/aleksandrsimonyan/fast-reid/configs/DukeMTMC/bagtricks_S50.yml
  debug_yolo: false
  features_model_weights: data/ext_models/DukeMTMC_BoT-S50.pth
  iou_thresh: 0.95
  out_logs_path: /Users/aleksandrsimonyan/Desktop/yolo_weights/predictions/fast_reid/logs
  sequence_folder: data/preds
  specific_videos: ['video_9746','video_1230','video_154','video_9149','video_3616','video_242','video_4653','video_1224','video_723','video_25','video_335.mp4','video_458.mp4','video_566.mp4','video_16.mp4','video_32.mp4']

  training_json: data/annot/object_tracking_valid_subset.json
  video_path: data/videos/train
  yolo_model_path: data/ext_models/YOLOXl-009_003-019-0.839273.pth
